### ISSUE TITLE
Datasets Preprocessing Code

### ISSUE THREAD

**Issue by awmirz** [DBook111/GD-Net#1]
Could you provide the preprocessing codes for the datasets please? They are initially different from the recommended folder hierarchy.

**Comment by DBook111** [comment]
Hello, I have submitted a new file named "**PreprocessDukeData**" 
You can directly run `sh data_download_and_preprocess.sh` to obtain the Duke dataset files. 
Note: The images are in numpy format. If you need other formats, you are free to process them.
